spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

  flyway:
    enable: true
    baseline-on-migrate: true

logging:
  level:
    org.springframework.jdbc.core: TRACE